version: "3.10"

services:
  app-react:
    build: ./client
    working_dir: /usr/src/front
    ports:
      - "3000:3000"
    networks:
      - mi_net
    depends_on:
      - smart-brain-api
    labels:
      - version=1.0.0

  smart-brain-api:
    container_name: smart-brain-api
    build: ./server
    working_dir: /usr/src/app
    environment:
      POSTGRES_USER: german
      POSTGRES_PASSWORD: secreto
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: db
    networks:
      - mi_net
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  db:
    container_name: db
    build: ./postgres
    environment:
      POSTGRES_USER: german
      POSTGRES_PASSWORD: secreto
      POSTGRES_DB: smart-brain
    ports:
      - "5432:5432"
    networks:
      - mi_net

networks:
  mi_net:
    driver: bridge
